//{{NO_DEPENDENCIES}}
// Include file generated by Microsoft Visual C++.
// Used by FICture2.rc.
//
#define IDC_MYICON                      2
#define IDD_FICTURE2_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDR_PNG_FOLDER                  129
#define IDR_PNG_FOLDER_UP               131
#define IDR_MENU_IMAGEBROWSER_CONTEXT   130
#define IDI_FICTURE2                    32512
#define IDM_CTX_OPEN_IMAGE              32771
#define IDM_CTX_OPEN_NEW_IMAGE          32772
#define IDM_CTX_CLOSE                   32773
#define IDM_CTX_BACKGROUND_COLOR        32774
#define IDM_CTX_FIT_TO_SCREEN           32775
#define IDM_CTX_TOGGLE_ALPHA            32776
#define IDM_CTX_TOGGLE_DIRECTORIES      32777
#define IDM_CTX_FOCUSED_BACKGROUND_COLOR 32778
#define IDM_CTX_TOGGLE_SAMPLING         32779
#define IDM_CTX_REGISTER_ASSOCIATIONS   32780
#define IDM_CTX_UNREGISTER_ASSOCIATIONS 32790
#define IDM_CTX_SAVE_SCREENSHOT         32791
#define IDM_CTX_CLEAR_RECENT            32792
#define IDM_CTX_RECENT_BASE             32800
#define IDM_CTX_RECENT_LAST             32819
#define IDM_CTX_REGISTER_THUMBNAIL_PROVIDER 32781
#define IDM_CTX_UNREGISTER_THUMBNAIL_PROVIDER 32782
#define IDM_CTX_ABOUT                   32783
#define IDM_CTX_SHOW_IN_EXPLORER        32784
#define IDM_CTX_OPEN_FOLDER             32785
#define IDM_CTX_ROTATE_LEFT             32786
#define IDM_CTX_ROTATE_RIGHT            32787
#define IDM_CTX_ROTATE_180              32788
#define IDM_CTX_ROTATE_RESET            32789
#define IDM_CTX_IMAGE_INFORMATION       32793
#define IDM_CTX_ALPHA_AUTO              32794
#define IDM_CTX_ALPHA_COVERAGE          32795
#define IDM_CTX_ALPHA_DATA              32796
#define IDM_CTX_MIP_BASE                32820
#define IDM_CTX_MIP_LAST                32851
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32852
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
